# Generated by Django 3.1.5 on 2021-07-07 18:18

from django.db import migrations, models
import django.utils.timezone
import searchapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, default=searchapp.models.id_genarator, max_length=7, null=True, unique=True)),
                ('destination_name', models.CharField(help_text='enter the client full names', max_length=50)),
                ('destination_email', models.CharField(help_text='enter the client email address', max_length=50, null=True)),
                ('destination_phone', models.CharField(help_text='enter the client phone number', max_length=15)),
                ('destination_address', models.CharField(help_text='enter the destination address', max_length=50)),
                ('my_name', models.CharField(help_text='enter your name here', max_length=50)),
                ('my_email', models.CharField(help_text='enter your email here', max_length=50)),
                ('content', models.CharField(default='i-Phone12, D&G Designers Hand Bag', max_length=100)),
                ('date_pushed', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(default=searchapp.models.limit_day)),
                ('current_location', models.CharField(max_length=20)),
                ('progress', models.IntegerField(blank=True, default=searchapp.models.next_day, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('waiting comfirmation', 'waiting comfirmation'), ('pending', 'pending'), ('delayed', 'delayed')], default=3, max_length=21)),
            ],
        ),
    ]
